config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'search', to: 'search#search'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'text']
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            title: {},
            text: {}
          }
        }
      }
    )
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'ik_smart', index_options: 'offsets'
      indexes :text, analyzer: 'ik_smart'
    end
  end
end

# Article.__elasticsearch__.create_index! force: true

# 1.7.0
# Delete the previous articles index in Elasticsearch
# Article.__elasticsearch__.client.indices.delete index: Article.index_name rescue nil

# Create the new index with the new mapping
# Article.__elasticsearch__.client.indices.create index: Article.index_name, body: { settings: Article.settings.to_hash, mappings: Article.mappings.to_hash }

# Index all article records from the DB to Elasticsearch
# Article.import

app/models/crew.rb
class Crew < ActiveRecord::Base
  has_many :roles
  has_many :movies, through: :roles

  validates :name, uniqueness: true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :movies

  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  validates :name, uniqueness: true

  has_and_belongs_to_many :genres

  has_many :roles
  has_many :crews, through: :roles

  mapping do
    indexes :id, index: :not_analyzed
    indexes :name
    indexes :synopsis
    indexes :year
    indexes :language
    indexes :country
    indexes :runtime,  type: 'integer'
    indexes :review,   type: 'float'
  end

  def as_indexed_json(options = {})
    self.as_json(only: [:id, :name, :synopsis, :year, :country, :language, :runtime, :review],
      include: {
        crews:  { only: [:id, :name] },
        genres: { only: [:id, :name] }
    })
  end

  class RelationError < StandardError
    def initialize(msg = "That Relationship Type doesn't exist")
      super(msg)
    end
  end

  def add_many(type, data)
    if type.in? ['Genre', 'Crew']
      self.send("#{type.downcase.pluralize}=", data.map do |g|
        type.classify.constantize.where(name: g).first_or_create!
      end)
    else
      raise RelationError
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :movie
  belongs_to :crew
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find params[:id]
  end

  def new
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  private
    def article_params
      params.require(:article).permit :title, :text
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.search((params[:q].present? ? params[:q] : '*')).records
  end

  def show
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @articles = []
    else
      @articles = Article.search params[:q]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <h3>
        <%= article.title %>
      </h3>
      <p>
        <%= article.text %>
      </p>
    </li>
  <% end -%>
</ul>
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>

  <% if not @article.nil? and @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to '<- Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to '<- Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAppBase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/movies/_movie.html.erb
<%= div_for movie do %>
  <h2><%= link_to movie.name, movie %></h2>
  <p><%= movie.synopsis %></p>
  <ul>
    <% movie.genres.each do |genre| %>
      <li><%= link_to genre.name %></li>
    <% end %>
  </ul>
<% end %>

app/views/movies/index.html.erb
<h1>All Movies</h1>

<nav class='navbar navbar-default'>
  <div class='container'>
    <%= form_tag movies_path, class: 'navbar-form navbar-left', role: 'search', method: :get do |f| %>
      <div class='form-group'>
        <%= text_field_tag :q, params[:q], class: 'form-control' %>
      </div>
      <%= button_tag "Search", class: 'btn btn-default', name: nil %>
    <% end %>
  </div>
</nav>

<%= render @movies %>

app/views/pages/about.html.erb
<h1>About</h1>

<p> This is a test about page.22 </p>

222


333



444
555


666
777
888
999
<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-success">Success</button>

app/views/pages/font-awesome.html.slim
= fa_icon "camera-retro"
/ => <i class="fa fa-camera-retro"></i>
br

= fa_icon "camera-retro", text: "Take a photo"
/ <i class="fa fa-camera-retro"></i> Take a photo
br
= fa_icon "chevron-right", text: "Get started", right: true
/ Get started <i class="fa fa-chevron-right"></i>
br
= fa_icon "quote-left 4x", class: "text-muted pull-left"
/ <i class="fa fa-quote-left fa-4x text-muted pull-left"></i>
br
br
= content_tag(:li, fa_icon("check li", text: "Bulleted list item"))
/ <li><i class="fa fa-check fa-li"></i> Bulleted list item</li>
br
= fa_stacked_icon "twitter", base: "square-o"
/ <span class="fa-stack">
/   <i class="fa fa-square-o fa-stack-2x"></i>
/   <i class="fa fa-twitter fa-stack-1x"></i>
/ </span>
br
= fa_stacked_icon "dollar inverse", base: "circle", class: "fa-5x"
/ <span class="fa-stack fa-5x">
/   <i class="fa fa-circle fa-stack-2x"></i>
/   <i class="fa fa-dollar fa-inverse fa-stack-1x"></i>
/ </span>
br
= fa_stacked_icon "terminal inverse", base: "square", class: "pull-right", text: "Hi!"
/ <span class="fa-stack pull-right">
/   <i class="fa fa-square fa-stack-2x"></i>
/   <i class="fa fa-terminal fa-inverse fa-stack-1x"></i>
/ </span> Hi!

app/views/search/search.html.erb
<h1>Articles Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @articles.each do |article| %>
    <li>
      <h3>
        <%= link_to article.try(:highlight).try(:title) ? article.highlight.title[0].html_safe : article.title,
          controller: "articles",
          action: "show",
          id: article._id%>
      </h3>
      <% if article.try(:highlight).try(:text) %>
        <% article.highlight.text.each do |snippet| %>
          <p><%= snippet.html_safe %>...</p>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>